[window]
opacity = 0.9
decorations = "none"

[terminal.shell]
program = "zellij"

[colors.primary]
foreground = "#bfbdb6"
background = "#0f1419"

[colors.normal]
black = "#131721"
red = "#f07178"
green = "#aad94c"
yellow = "#e6b450"
blue = "#59c2ff"
magenta = "#d2a6ff"
cyan = "#73b8ff"
white = "#bfbdb6"
